# TF Syntax BASICS

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.14.0


In [3]:
hello = tf.constant("Hello")
world = tf.constant("world")

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
# for printing sth in tensorflow you need to run session first then u can run anything else 
# for creating Session 

Tensor("Const:0", shape=(), dtype=string)


In [6]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [7]:
print(result)

b'Helloworld'


In [2]:
# for addition in tensorflow

a = tf.constant(10)
b = tf.constant(20)

c = a+b
print(c)

Tensor("add:0", shape=(), dtype=int32)


In [3]:
# for runing the operations 

with tf.Session() as sess:
    result = sess.run(c)

In [4]:
result

30

In [5]:
const = tf.constant(10)

In [6]:
fill_mat = tf.fill((4, 4), 10) # create a matrix of 4x4 filled with value 10

In [7]:
# for runing the operations 

with tf.Session() as sess:
    result = sess.run(fill_mat)

In [8]:
result

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [12]:
const = tf.constant(20)

In [13]:
fill_mat = tf.fill((4, 4), 10)
myzeros = tf.zeros((4, 4))
myones = tf.ones((4, 4))

In [14]:
# for random normal distributed matrix
myrandn = tf.random_normal((4, 4), mean = 0, stddev = 1.0)

In [15]:
myrandu = tf.random_uniform((4, 4), minval = 0, maxval = 1)

In [16]:
# I m gonnna create a list of my operations that i want to execute alltogether

my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [17]:
with tf.Session() as sess:
    result = sess.run(my_ops)

In [18]:
result

[20, array([[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]), array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32), array([[-0.08570628, -0.13368247, -0.72483915,  0.6236135 ],
        [-1.7756761 ,  0.8063454 , -1.9290072 , -0.00894255],
        [-0.8172856 , -1.0021296 , -0.8642136 , -1.1382757 ],
        [ 0.49303707,  0.08941483, -0.58993423,  0.93726593]],
       dtype=float32), array([[0.83080673, 0.8235432 , 0.03341889, 0.31248164],
        [0.3373369 , 0.98137856, 0.92313683, 0.85726655],
        [0.4550531 , 0.81816614, 0.78022444, 0.18932712],
        [0.9970125 , 0.08945847, 0.71331584, 0.3850522 ]], dtype=float32)]

In [19]:
# OR there is also an another way of running tensorflow session
# this technique is usefull in only jupyter notebook

sess = tf.InteractiveSession()

# isky neechy sy har cell k lye session active ho jae ga so u dont need to initialise session everytime 

In [20]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

20


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.1504392   1.2266557   1.8404409  -0.18179922]
 [ 0.24913535  1.234196   -1.1331968   0.94609845]
 [-1.4210455  -0.6764168   0.68199956 -0.14507976]
 [-0.7225157  -1.3441039  -0.38090378  1.3630817 ]]


[[0.2093699  0.9137763  0.07970548 0.2587391 ]
 [0.7256491  0.24839318 0.6528944  0.36930597]
 [0.28235245 0.02567697 0.0818243  0.70847654]
 [0.20025265 0.07343471 0.47993636 0.84515667]]




In [16]:
# instead of calling session everytime u can use eval() function as well

In [17]:
for op in my_ops:
    print(op.eval())
    print("\n")

20


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 8.3601695e-01 -1.5227368e+00  9.5854962e-01 -2.8647552e+00]
 [-6.6131544e-01  1.1326742e+00 -1.1655380e+00  9.8345600e-02]
 [ 2.2449224e+00  8.6572647e-01 -1.3072995e+00  4.8061568e-01]
 [ 9.7349393e-01 -1.6164181e+00  2.7743529e-03 -6.9651479e-01]]


[[0.10731232 0.21881986 0.24409986 0.76574373]
 [0.606107   0.8821547  0.6615921  0.85991895]
 [0.7440176  0.29988945 0.97378993 0.24048817]
 [0.43253613 0.31970704 0.790159   0.43987536]]




In [ ]:
# Matrix multiplication 

In [18]:
a = tf.constant([ [1, 2], [3, 4] ])  # 2 x 2 matrix
b = tf.constant([ [10], [100] ])

In [19]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [20]:
result = tf.matmul(a, b)

In [21]:
sess.run(result)

array([[210],
       [430]])

In [22]:
result.eval()

array([[210],
       [430]])